ipython_notebooks/Tutorials/13 GST on 2 qubits.ipynb
(Without the space, the formatting is not recognized by whatever
Markdown parser a current Jupyter 4.1.0 installation uses.)
=> Fix headline formatting in Tutorial 13 [nfc]

.gitignore
This seems to be a C extension artifact that didn't get ignored.
(It's a small change, but I made a PR because I don't know if things like this are actually bugs or intentional)
=> gitignored fastopcalc.cpp

.travis.yml
Simple patch, but I want the green-light from @enielse before merging.
Supporting both 3.7 and 3.5 in CI is a ton of extra build time without a lot of payoff if we don't actually care about 3.5 support, so maybe think about dropping 3.5.
=> Moved CI runner up to xenial, python 3.7

packages/pygsti/objects/operation.py, packages/pygsti/objects/polynomial.py, packages/pygsti/objects/slowreplib.py, packages/pygsti/objects/spamvec.py, packages/pygsti/objects/term.py
Adds some finishing touches onto the work of the previously merged feature-directterms branch.  Rob can decide whether/when to merge this into develop as is convenient with the reformatting work.
=> Updates most SPAM vecs & ops to work with pruned-path term calcs.

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CONTRIBUTING.md
Adds contributor guidelines & issue templates. Closes #60 
Github reads issue templates from `master`, so I'm requesting this be merged directly to `master` instead of `develop`. This only adds Github content, so there's no reason to wait to include in a release. But you may also want to merge it to `develop` just so the refs are there.
Also, be aware that the template links (and some links on the wiki) are broken until this is merged to master.
=> Contributor guidelines

packages/pygsti/construction/modelconstruction.py, packages/pygsti/construction/nqnoiseconstruction.py, packages/pygsti/objects/cloudnoisemodel.py, packages/pygsti/objects/localnoisemodel.py, packages/pygsti/objects/operation.py, packages/pygsti/objects/opfactory.py, packages/pygsti/objects/processorspec.py, test/test_packages/drivers/testCalcMethods1Q.py, test/test_packages/drivers/testNQubit.py, test/test_packages/extras/test_idt.py, test/test_packages/objects/testLabels.py
A second installment of functionality to ease model-building, this PR adds a number of new factory types an more integration of these factories (e.g. into ProcessorSpec and allowing unitary-returning-functions to be passed in `nonstd_gate_unitaries` arguments).
=> Feature modelbuilding

.gitignore, .travis.yml
The Travis CI deploy phase was previously running for every successful job, which doesn't match our use case. Deployment now runs in a dedicated stage, only on tag builds.
Also gitignores `packages/pyGSTi.egg-info`. The same path but lower-case was already gitignored. Not sure what that was used for.
Also disabled Travis CI building wheels on deployment. PyPI unconditionally rejects `linux_x86_64` wheels, which is our build platform. Might be able to get it building using the specific environment PyPI wants on Travis, but in the meantime, we'll just have to manually push wheels.
=> v0.9.8 CI hotfix

packages/pygsti/tools/matrixtools.py
Closes #87 
Compensates for scaling factor introduced in 434866d which caused assertion in `matrixtools.unitary_superoperator_matrix_log` to fail
=> Close "AssertionError when generating report: _np.linalg.norm(_spl.expm(logM) - M) < 1e-8) "

packages/pygsti/baseobjs/basis.py, packages/pygsti/baseobjs/basisconstructors.py, packages/pygsti/baseobjs/opttools.py, test/unit/baseobjs/test_opttools.py
`opttools.cache_by_hashed_args` should be deprecated in favor of the standard `functools.lru_cache` which performs effectively the same functionality, with the added advantage of adjustable cache size and low-level optimization.
Usages of `cache_by_hashed_args` have been replaced with `lru_cache(maxsize=128)`. The value of `maxsize` should be adjusted based on use case, but I can't say for sure. See [the documentation](https://docs.python.org/3.7/library/functools.html#functools.lru_cache) for more about `maxsize`
This patch sets `cache_by_hashed_args` to be deprecated by v0.9.9.
=> Deprecate `opttools.cache_by_hashed_args`

packages/pygsti/report/factory.py, packages/pygsti/report/merge_helpers.py, packages/pygsti/report/templates/drift_html_report/main.html, packages/pygsti/report/templates/drift_html_report/tabs/AjaxError.html, packages/pygsti/report/templates/idletomography_html_report/main.html, packages/pygsti/report/templates/idletomography_html_report/tabs/AjaxError.html, packages/pygsti/report/templates/offline/pygsti_dashboard.js, packages/pygsti/report/templates/standard_html_report/main.html, packages/pygsti/report/templates/standard_html_report/tabs/AjaxError.html, packages/pygsti/report/workspace.py
Adds 'embed_figures' advanced option to report generation functions (e.g. create_standard_report) that defaults to `True`.  When `False`, separate figure files are created in a figures/ subdirectory, allowing very large reports to be displayed efficiently (with the help of a web browser so the Ajax calls work).
=> Feature distributed report

packages/pygsti/__init__.py
As of 8aaa12b, the project source was moved to the repo root. @enielse
brought up a good point that users who have installed pyGSTi as an egg
may be confused as to why their install is suddenly broken. By leaving
a small script at /packages/pygsti we can warn affected users to
reinstall pyGSTi.
=> Added warning message to /packages/pygsti.

pygsti/construction/__init__.py, pygsti/tools/legacytools.py
Based on conversations with @enielse.
This patch permits legacy modelpacks (which have been refactored into `pygsti.modelpacks.legacy`) to be imported from the old path (`pygsti.construction`). The import mechanism is wrapped to emit a warning message when importing from the deprecated path.
The actual wrapping of the import mechanism checks for python version >= 3.7, where a module-level `__getattr__` would be available. If it's available, it uses that, and if not, it wraps the module in a `ModuleType` object using a helper function added to `tools.legacytools`
=> Deprecate import of legacy modelpacks from `pygsti.construction`

setup.py
Since we provide pure-python alternatives to all cython extensions, setup.py should still install pyGSTi if extension compilation fails. This patch does that, emitting a warning on compilation failure. Additionally, cythonization failures are allowed and excluded. Developers should pay special attention when developing cython extensions, as compilation errors are now less obvious.
=> Extension compilation fallback

pygsti/objects/povm.py
The bulk of this work was committed within the feature-regularization pull request, as this branch had been merged into that one previously.  This pull request serves mostly as a placeholder reminding us that we updated **most of the function and function-argument names in pyGSTi to conform to the lowercase_with_underscores PEP8 naming convention**.
We have not, at this point, changed all of the (public) class attributes to follow this convention.  So currently within pyGSTi the module names, class names, function names, and function-argument names all follow PEP8 conventions, but class attributes may not.
=> Adds PEP8 naming compliance to function names and arguments.

.travis.yml, pygsti/extras/drift/driftreport.py, pygsti/objects/smartcache.py, pygsti/report/notebook.py, pygsti/report/plothelpers.py, pygsti/report/plotly_plot_ex.py, setup.py
Closes #126 
Adds a `no_mpi` extras install target, which is equivalent to the `complete` target but without the `mpi4py` requirement.
Incidentally, also removes the redundant `nose testing` extras install target.
=> Adds "no-MPI" extras target

pygsti/algorithms/gaugeopt.py, pygsti/objects/gaugegroup.py, pygsti/protocols/gst.py, pygsti/report/workspacetables.py
Adds functionality to perform gauge optimizations whereby the Frobenius distance between a transformed *target* model and a fixed estimated model is minimized.  This differs from the usual optimization where the target model is fixed and the estimate is gauge-transformed (the Frobenius distance is *not* invariant under this difference).
A new `"stdgaugeopt-tt"` suite has been added to allow testing of this tweaked means of gauge optimization.  If it works well it may take over as the default (but it hasn't yet).  
The gauge-robust gates table, however, uses the new method now, as it's calculations seem particularly helped by the update (and the gauge-robust metrics table is itself in an experimental state).
=> Feature target gaugeopt

pygsti/algorithms/core.py, pygsti/objects/model.py, pygsti/protocols/estimate.py, pygsti/protocols/gst.py, pygsti/report/factory.py, pygsti/report/plothelpers.py, pygsti/report/workspaceplots.py, pygsti/report/workspacetables.py, pygsti/tools/likelihoodfns.py
This new property defaults to the usual .num_params, but can be set
independently to allow more flexibility in tuning the model tests
within reports and other functions.  This commit moves the logic
involved in testing whether to use the number of non-gauge parameters
instead of the total parameters to the default .num_modeltest_params
property function, simplifying other functions.  It also adds a
memory limit that can be set to avoid computing the number of nongauge
parameters when it would require too much memory.
=> Adds a new Model.num_modeltest_params property

jupyter_notebooks/Examples/CirqIntegration.ipynb, pygsti/objects/dataset.py
I ended up adding the import method to DataSet because that seemed to fit well. I can move it elsewhere if you'd like. I also added a jupyter notebook showing how to run everything. Feel free to include it or discard it.
=> Added DataSet.add_cirq_trial_result method to import Cirq.TrialResult objects

pygsti/objects/implicitmodel.py, pygsti/objects/model.py, test/unit/objects/test_localnoisemodel.py
This includes Erik's suggested fixes + a modification to _is_primitive_povm_circuit_lbl to allow marginalized primitive POVM labels to be detected as primitive as well.
The new test (`test_marginalized_povm`) fails if custom `qubit_labels` are used, as in other `LocalNoiseModel` tests. I think this is a related but separate marginalization bug to what I'm trying to fix in this PR. The relevant portion of error message:
```
File "/Users/sserita/Documents/repos/pyGSTi/pygsti/objects/povm.py", line 1468, in <listcomp>
indices_to_keep = set([list(all_sslbls).index(l) for l in sslbls_after_marginalizing])
ValueError: 0 is not in list
```
This can be reproduced by adding `qubit_labels=['qb{}'.format(i) for i in range(nQubits)],` into the constructor call of `mdl_local` in the new test.
=> Bugfix marginalized povm

.github/workflows/extras.yml
Really this is testing whether or not disabling the on: pull_requests fixes the unnamed workflow since direct pushes to develop seem to have no issues with the automated push to beta.
=> Split out extra tests, disable on PRs

.github/workflows/extras.yml, .github/workflows/main.yml, pygsti/protocols/modeltest.py
Two small bugfixes:
**Unpinning cvxpy from 1.1.7**
1.1.9 fixed the versioning issues with 1.1.8,  and 1.1.10 may be needed for newer numpy versions.
**Adding badfit_options as an auxfile for ModelTest**
This matches the behavior in GateSetTomography and was needed as GSTBadFitOptions could not be JSON-serialized when testing with wildcard during SGST analysis.
=> Bugfix cvxpy and modeltest

.gitignore, pygsti/construction/modelconstruction.py, pygsti/construction/nqnoiseconstruction.py, pygsti/objects/operation.py, pygsti/tools/internalgates.py, test/unit/construction/test_modelconstruction.py, test/unit/construction/test_nqnoiseconstruction.py, test/unit/objects/test_operation.py
Added the StaticStandardOp class and reworked the crosstalk-free model construction for more explicit error specification.
Probably more work could be done on extending new error specification API to the cloud noise model construction, but that seems less clear since that construction relies heavily on LindbladOps. In the meantime, this PR could already be useful in the feature-chp-revive branch.
=> Feature std static op

pygsti/objects/circuit.py, pygsti/tools/internalgates.py
Very small, local changes. Adds "Gczr" as a standard gate (a controlled Z(theta) rotation gate), adds the ability to automatically convert circuits containing this gate into QASM, and adds some details to QASM-conversion-related functions' docstrings.
=> Feature qasm conversion updates

pygsti/io/stdinput.py
Fixes a bug Tim encountered in the DirectRB tutorial,
where circuits with no outcome:count pairs could not be reshaped
during dataset loading.
=> Guard against empty circuit lists in dataset load.

jupyter_notebooks/Tutorials/algorithms/advanced/CircuitSimulation-CHP.ipynb, pygsti/baseobjs/basis.py, pygsti/construction/modelconstruction.py, pygsti/evotypes/densitymx_slow/statereps.py, pygsti/forwardsims/chpforwardsim.py, pygsti/forwardsims/forwardsim.py, pygsti/forwardsims/weakforwardsim.py, pygsti/modelmembers/povms/composedpovm.py, pygsti/models/localnoisemodel.py, test/unit/construction/test_modelconstruction.py, test/unit/objects/test_composed_spam.py, test/unit/objects/test_spamvec.py
The recent large refactor duplicated some of the work in an existing
(feature-noiseop-spamvec) branch and it would have been difficult for
git to merge it correctly.  This commit is the result of taking all
the new commits on that branch and applying/adjusting them on top
of the post-refactored code.
**Text from the original PR (which may not all be entirely relevant now):**
Several changes designed to allow general noisy operations after state prep/before measurement.
- New ComposedSPAMVec/POVM that takes a general LinearOperator and a ComputationalSPAMVec/ComputationalBasisPOVM
- CHPForwardSimulator updated to handle ComposedSPAMVec/POVM (rather than LinearOperator/ComputationalBasisPOVM)
- create_crosstalk_free_model updated to allow Composed instead of Lindblad for SPAMVec/POVM …
=> feature noisy spamvec: manually merged updates from feature-noiseop-spamvec

pygsti/circuits/circuit.py, pygsti/circuits/circuitparser/fastcircuitparser.pyx, pygsti/circuits/circuitparser/slowcircuitparser.py, pygsti/io/stdinput.py, pygsti/models/modelnoise.py, test/unit/io/test_circuitparser.py, test/unit/objects/test_circuit.py
**Adds "compilable" layer indices metadata to `Circuit` objects.**
Adds to circuits a `compilable_layer_indices` attribute that tracks which circuit layers are "compilable".  This can mean different things in different contexts, since it's just bookkeeping metadata, but its intended use is to indicate which circuit layers can be modified and combined with the following layer by a hardware compiler.  By default circuits have no compilable layers, and a circuit's `.compilable_layer_indices` is `None`.  This corresponds to having a barrier (a directive telling the hardware compiler that it *cannot* combine or modify the gates from one layer to the next) after every layer.
Which layers are compilable can be parsed from and written in the string representation of a circuit by following a layer …
=> Feature circuit barriers

test/test_packages/extras/test_interpygate.py
Adjust the numerical comparisons in  interpygate regression tests for the combination of new interpolation + Brandon's bugfix.
=> Update interpygate regression tests

.github/workflows/extras.yml, pygsti/algorithms/compilers.py, pygsti/algorithms/mirroring.py, pygsti/algorithms/randomcircuit.py, pygsti/algorithms/rbfit.py, pygsti/baseobjs/qubitgraph.py, pygsti/data/dataset.py, pygsti/evotypes/stabilizer/opreps.pyx, pygsti/forwardsims/termforwardsim_calc_generic.py, pygsti/modelmembers/operations/composederrorgen.py, pygsti/modelmembers/states/computationalstate.py, pygsti/models/oplessmodel.py, pygsti/objectivefns/wildcardbudget.py, pygsti/optimize/customsolve.py, pygsti/tools/fastcalc.pyx, pygsti/tools/matrixmod2.py, pygsti/tools/rbtheory.py, pygsti/tools/symplectic.py, test/test_packages/drivers/testCalcMethods1Q.py
Fixes a number of bugs related to using "int" vs "np.int64" throughout pygsti.  This caused crashed (some exceptions, some segfaults!) on Windows, where using a numpy dtype of "int" specifies a 32-bit integer, conflicting with other uses in pyGSTi of np.int64.  This PR attempts to convert all usages to np.int64, and at least gets all of the unit and system tests to pass on a windows build.
=> Bugfix windows integers

pygsti/models/cloudnoisemodel.py, pygsti/models/localnoisemodel.py, pygsti/models/modelconstruction.py
Adds `'pad_1Q'` option for `implicit_idle_mode` arguments for local- and cloud-noise models.
This PR just adds another, hopefully useful, option for the `implicit_idle_mode` of constructed local and cloud noise models. 
The new `'pad_1Q'` value creates a layer rule where a model's 1Q idle gate is applied only to the idling qubits within a circuit layer.  (Entirely empty layers are modeled by composing the 1Q idle on each qubit.)
=> Feature implicit idle mode

pygsti/models/modelconstruction.py, pygsti/processors/processorspec.py, pygsti/protocols/gst.py, test/unit/construction/test_modelconstruction.py, test/unit/objects/test_processorspec.py
Adds SPAM and instrument elements to the `QubitProcessorSpec` class, allowing processor specifications to specify more than just the available gates API.
This is particularly useful for working with models that have non-default SPAM (and/or instrument) elements, as these elements should now be able to be captured by the processor spec and therefore held within an experiment design as needed (e.g. for running GST).
=> Feature add SPAM elements to processor specs

pygsti/algorithms/gaugeopt.py, pygsti/evotypes/densitymx/opreps.pyx, pygsti/evotypes/densitymx_slow/opreps.py, pygsti/evotypes/stabilizer/opreps.pyx, pygsti/evotypes/statevec/opreps.pyx, pygsti/evotypes/statevec_slow/opreps.py, pygsti/io/stdinput.py, pygsti/modelmembers/operations/__init__.py, pygsti/modelmembers/operations/denseop.py, pygsti/modelmembers/operations/fullunitaryop.py, pygsti/modelmembers/operations/opfactory.py, pygsti/models/explicitcalc.py, pygsti/models/explicitmodel.py, pygsti/models/modelconstruction.py, pygsti/models/qutrit.py, pygsti/protocols/confidenceregionfactory.py, pygsti/tools/matrixtools.py, pygsti/tools/optools.py, test/unit/drivers/test_bootstrap.py
**Fixes an algebra bug in how Hessian matrices were being projected.**
This fix potentially affects *all* error bar calculations, and while we hope it doesn't do so drastically, it would be worthwhile to recompute suspicious error bars after this fix has been applied.  
This PR also introduces some new functions for converting between unitary and superoperator matrices.  In particular, it renames `unitary_to_process_mx` to `unitary_to_std_process_mx` and `process_mx_to_unitary` to `std_process_mx_to_unitary` and deprecates the old names.  It also adds new `superop_to_unitary` and `unitary_to_superop` functions (all in `pygsti.tools`).
=> Bugfix hessian projection

jupyter_notebooks/Tutorials/algorithms/advanced/CircuitSimulation-CHP.ipynb, pygsti/evotypes/chp/opreps.py, pygsti/evotypes/chp/statereps.py, pygsti/forwardsims/chpforwardsim.py, pygsti/forwardsims/weakforwardsim.py, pygsti/modelmembers/operations/opfactory.py
Three major things are done here:
1. This takes the important bugfixes of the chp-many-qubit-fixes branch and ports them to a post 0.9.10 pyGSTi.
2. The chp_ops property in the OpReps is turned into a method to make it easier to consistently pass RNG in from the WeakForwardSimulator.
3. The CHPForwardSimulator is cleaned up. In particular, state/povm handling is streamlined.
=> Feature chp fix updates

jupyter_notebooks/Examples/1QGST-InterpolatedOps.ipynb, jupyter_notebooks/Examples/2QGST-CreatingModels.ipynb, jupyter_notebooks/Examples/2QGST-ErrorBars.ipynb, jupyter_notebooks/Examples/2QGST-RunningIt.ipynb, jupyter_notebooks/Examples/BootstrappedErrorBars.ipynb, jupyter_notebooks/Examples/ContextDependence.ipynb, jupyter_notebooks/Examples/GOpt-AddingNewOptimizations.ipynb, jupyter_notebooks/Examples/GOpt-NonIdealTargets.ipynb, jupyter_notebooks/Examples/Leakage.ipynb, jupyter_notebooks/Examples/ModelMemberGraph.ipynb, jupyter_notebooks/Examples/QutritGST.ipynb, jupyter_notebooks/Examples/Reports-LGSTonly.ipynb, pygsti/report/merge_helpers.py, pygsti/report/reportables.py
=> Bugfixes for Example notebooks.

pygsti/algorithms/mirroring.py
Fixed a bug in circuit mirroring of circuits containing Gczr(theta) gates, which created incorrect mirror circuits whenever there were parallel two-qubit gates in a layer. Created non-definite-outcome circuits, so will have created obviously faulty data for anyone who used it.
=> Fixed bug in circuit mirroring for cz(theta) circuits

.gitignore, pygsti/models/modelconstruction.py
The call signature for constructing gauge groups has changed so this needed to be updated in modelconstruction.
=> Minor GaugeGroup related Bugfix

pygsti/algorithms/compilers.py, pygsti/algorithms/randomcircuit.py, pygsti/tools/matrixmod2.py
**Adds the ability to seed Clifford compilations used in RB so deterministic behavior results**
Plumbs a `RandomState` object through functions in `compilers.py` and `matrixmod2.py` so that the randomness used therein can be seeded properly.  This PR also removes a duplicate `done_editing` call in `randomcircuit.py` that I stumbled upon as I was making the main updates.
I think (& hope) that this PR may fix a long-standing issue of the pyGSTi unit tests occasionally failing because of an RB circuit mismatch.  This erroring could be "fixed" by simply rerunning the unit tests again, which was suspicious and unnerving.
=> Bugfix matrixmod2 determinism

pygsti/baseobjs/__init__.py, pygsti/baseobjs/mongoserializable.py, pygsti/io/__init__.py, pygsti/io/metadir.py, pygsti/io/mongodb.py, pygsti/io/readers.py, pygsti/io/writers.py, pygsti/objectivefns/objectivefns.py, pygsti/protocols/confidenceregionfactory.py, pygsti/protocols/estimate.py, pygsti/protocols/protocol.py, pygsti/protocols/treenode.py, setup.py, test/unit/io/test_mongo.py
**Adds ability to serialize pyGSTi objects to a MongoDB database.**
Leverages the framework used to save pyGSTi objects to json files within a filesystem hierarchy to alternatively save these objects to a MongoDB database.  This medium provides some potential benefits over a filesystem in that it's easier to share and distribute (see *sharding* MongoDB lingo), and can be made robust through transactions and automated backups.
This PR represents the first implementation of a MongoDB serialization interface, adding MongoDB counterparts to many of the file I/O functions.  In particular, it adds `write_to_mongodb` methods for experiment design, protocol data, and protocol results objects, and adds `pygsti.io.read_edesign_from_mongodb`, `pygsti.io.read_data_from_mongodb`, and …
=> Feature mongodb serialization

pygsti/algorithms/fiducialpairreduction.py, pygsti/algorithms/germselection.py, test/test_packages/algorithmsb/testGermSelection.py
This branch introduces a new greedy search algorithm for performing per-germ FPR. This algorithm leverages the same low-rank update machinery used to generate speedups for germ selection. Due to the nature of the low-rank updates used, this utilizes an objective function based on the trace of the psuedo-inverse of a candidate fiducial set's Jacobian instead of the minimum eigenvalue (these should largely track with each other though). In the course of developing this a number of edge cases were revealed in the low-rank update code which didn't arise when testing germ selection. These have been patched, and as a nice side-effect the fixes actually result in a modest performance boost for germ selection too.
Smaller changes included in the branch include:
- bugfixes for numpy data type …
=> Feature fpr algorithm performance

pygsti/algorithms/fiducialselection.py, pygsti/algorithms/germselection.py
This branch implements a new greedy search algorithm that leverages the same low-rank update tools now available for germ selection and FPR. This is specifically useful for accelerating fiducial selection for many-qubit systems in the 4+ qubit range (for 3 or less the existing algorithms seem to run quick enough for most applications). This new greedy search algorithm only works with an objective function based on the psuedoinverse-trace. Other notable changes in this branch:
- Added additional flexibility to the specification of candidate fiducial sets. Before we could only specify a maximum fiducial length and then all circuits up to that length would be used in the search space. Now the API matches the one used for germ selection were we can specify a dictionary with keys corresponding …
=> Feature fidsel performance

pygsti/baseobjs/qubitgraph.py, pygsti/circuits/circuit.py, pygsti/circuits/circuitstructure.py, pygsti/data/datacomparator.py, pygsti/extras/crosstalk/core.py, pygsti/report/workspace.py, pygsti/report/workspaceplots.py, pygsti/tools/group.py, test/unit/objects/test_qibo_evotype.py
I took an initial pass at fixing the calls to the newly deprecated dtype aliases. I think I got everything in our codebase, but there are some broken calls in qibo that cause the import to die, and related unit tests to fail, so these have been temporarily disabled. There are a couple more unit tests that are failing, but these are related to germ selection and seem to be broken for a different reason (I suspect for a disjoint numpy change given the error messages). For the sake of having a clean commit history I am going to fix those problems on another branch where I also look into the edge case @enielse showed me about when the initial set of germs in germ selection is empty. So I'm requesting we merge this in even though there are still some failing tests.
=> Bugfix numpy deprecations

pygsti/algorithms/germselection.py
This should fix the last two failing unit tests, which I believe were failing due to a numpy 1.24.0 related change (though not one easily ascertained from the changelog). These lines of codes haven't been touched in a very long time, so there isn't any other reason I can think of for them suddenly breaking.
Anyhow, I haven't yet resolved the other problem @enielse noticed when the list of forced germs is empty, but I don't think I'll get around to that until after we push the release (I can aim for whenever the first hotfix we push to master is).
=> Bugfix germsel initialization

pygsti/baseobjs/qubitgraph.py, pygsti/tools/sharedmemtools.py
Straightforward bugfix related to the shared memory module of the multiprocessing library expecting default system integers for the size argument for some reason, which on windows are 32-bit. I think the second fix has already been subsumed by other numpy dtype fixes.
=> Bugfix neverending windows integers

pygsti/algorithms/germselection.py, pygsti/protocols/gst.py, pygsti/protocols/protocol.py, pygsti/protocols/rb.py, pygsti/protocols/vb.py, test/unit/protocols/test_protocols.py
**Adds `map_qubit_labels` methods of experiment design classes.**
These methods make it easy and convenient to change the qubit labels of an experiment design.  This makes it possible to store "template experiment designs" that can be used to produce many replicas of themselves on different sets of qubits.  This functionality is implemented for `CombinedExperimentDesign` and `SimultaneousExperimentDesign` objects, and so can be applied to entire trees of experiment designs.
Basic unit tests were added.
=> Feature edesign map-qubit-labels

pygsti/report/workspace.py
This PR patches some deprecated function calls from the python inspect module that have been deprecated as of python 3.11. Patch courtesy of @sserita.
=> Replace deprecated function calls to inspect module

pygsti/protocols/gst.py, pygsti/report/factory.py
This patch addresses a bug in the 1D wildcard models that resulted from a mismatch in the gauge optimization settings used in different places in the code. We now have some basic plumbing for the GSTGaugeOptSuite that pipes the different gauge optimizations through to the badfit estimate code and makes sure that we are consistent. Also makes the wildcard models switchable on the gauge optimization in the report generation for cases where we have more than one gauge optimization used.
This patch follows up on the initial patch @enielse made for this issue in commit 283803466ab92fd2cd6c838a906625ef96c20565
(I actually hadn't noticed there was a recent commit targeting this until putting the PR together, funny that we both ran into this in such close succession!)
=> Patch wildcard gauge optimization bugs

pygsti/algorithms/germselection.py, test/unit/algorithms/test_germselection.py
This PR adds bugfixes related to the handling of the 'force' argument in the germ selection algorithms. Three different issues were identified and have been patched:
1. There was no support for the case where force=None, and as such the initial germ set fed into the greedy search loop was empty. This case is now fully supported, with the algorithm doing a greedy initialization (choosing the germ from the candidate list with the highest score) to select the first germ.
2. When passing in a user-specified list of germs for the value of force an edge case arose when, for various possible reasons, the user-specified list included circuits that were not part of the search space. There is now logic to detect when this happens and explicitly add these extra germs to the search space if required. …
=> Bugfix forced germs

pygsti/tools/edesigntools.py, test/unit/tools/test_edesigntools.py
Straightforward utility function to pad out edesigns with idle lines.
=> Adds edesign padding and tests.

pygsti/modelmembers/operations/lindbladcoefficients.py, pygsti/objectivefns/objectivefns.py
This PR improves performance of 2-qubit GST 
* Vectorize `LindbladCoefficientBlock.from_vector`. Replacing the loop over `i` reduces the overhead for 2-qubit gst (where `num_bels=15`). In microbenchmarks this is a factor 6 faster
* Replace call to `_np.sum` to direct call of `sum()`. In microbencmark this is 33% faster.
=> Improve performance of GST

pygsti/modelmembers/povms/basepovm.py, pygsti/modelmembers/povms/complementeffect.py, pygsti/modelmembers/povms/conjugatedeffect.py
Plumbs the 'called_from_reduce' argument of TPPOVM.__init__ into ComplementPOVMEffect and ConjugatedStatePOVMEffect so that effect gpindices aren't allocated during the intialization of a TPPOVM that originates via a __reduce__ call.  Also adds logic to BasePOVM to avoid copying effect vectors, which would reset their gpindices and cause allocation down the line.  This bugfix may also fix issues with copying TPPOVM objects via, e.g., deepcopy, as this uses the same control path as pickle.  Lightly tested on a 1Q TP-parameterized model.
=> Fixes gpindices initialization issue in TPPOVM.

jupyter_notebooks/Tutorials/objects/advanced/OperationFactories.ipynb, pygsti/modelmembers/operations/opfactory.py
**Alters behavior of `EmbeddingOpFactory` to pass state space labels of operations being created through to a contained (embedded) operation factory object.**
Previously, when an EmbeddingOpFactory would "blank out" (set to `None`) the `sslbls` argument passed to the contained op-factory's `create_op` call.  Now this argument receives the original `sslbls` and so the contained factory can use this information to create different operations depending on what the operation's target qubits are.
This PR updates assertions in `UnitaryOpFactory` and an example in the operation factory tutorial that no longer hold in generatlity.
=> Enhances EmbeddingOpFactory to be used to create target-qubit-dependent operation factories

pygsti/models/explicitmodel.py, pygsti/models/modelconstruction.py, pygsti/report/reportables.py
Several small fixes to allow StandardGST protocols and reports to work with models that use instruments. Includes several fixes for converting between explicit models and processor specs to no longer drop instruments.
=> Bugfix pspec instrument stdgst

pygsti/modelmembers/operations/experrorgenop.py, pygsti/tools/optools.py
* `np.math` was an alias for the stdlib math module and has been deprecated
* Conversion of an array with ndim > 0 to a scalar is deprecated
=> Fix numpy deprecation warnings

pytest.ini, test/unit/extras/interpygate/test_construction.py, test/unit/modelmembers/test_operation.py, test/unit/objects/test_objectivefns.py
This should resolve #361.
This branch has latest develop as its base. It had 6 failing tests when I started. Five of those failing tests were due to a wrong version of a dependency (qibo) I got when I installed pyGSTi. The other failing test was due to a missing dependency. I've modified this last failing test so that it handles the missing dependency gracefully. I'd like it if the other five tests also gracefully handled a wrong dependency version, but I'll put that off for now as issue #363.
The initial change I made in this PR was just to ``pytest.ini``. Then I needed to fix some broken tests.
=> Help pytest find tests

pygsti/io/writers.py
This PR patches the bug reported in #321. Previously the function `pygsti.io.write_empty_protocol_data` had the assumptions of qubits and that the readout was done in the standard basis hardcoded in. This lead to unexpected behavior when using models (really processor specs) with non-standard readout or even qudits with standard readout for dim>2. This PR adds in support for both of these things. For qudits this includes support for mismatching dimensions on the subsystems. This currently doesn't support multiple POVMs, and for non-standard POVMs if there were more than one we currently simply take the first in the list.
Let me know if you have any questions or concerns.
=> Add support for non-standard POVMs and qudits to write_empty_protocol_data

.github/CODEOWNERS
Implement a CODEOWNERS file for pyGSTi to modernize our PR pipeline.
This branch/PR will stay open as we get volunteers in. Edit: We now have all the volunteers and subteams set up.
=> Implement CODEOWNERS

.github/workflows/autodeploy.yml, .github/workflows/extras.yml, .github/workflows/main-mac.yml, .github/workflows/main-minimal.yml, .github/workflows/main.yml, .github/workflows/manualdeploy.yml, .github/workflows/notebook.yml, .github/workflows/testdeploy.yml
This includes several quality-of-life and deprecation runner updates and addresses #387.
- MacOS runners are oversubscribed and 10x more expensive, and rarely break due to OS specific issues not caught by Linux tests. Therefore, MacOS tests are now only run on `beta` and `master`.
- Bugfix/feature branches now only test the lowest and highest supported Python versions - this should be sufficient to flag any deprecation or missing language feature problems and cuts down the runtime on these branches by 2x. (Combined with no MacOS tests, this takes the number of runners needed from 12 to 4).
- The runner versions were updated to `-latest`, bumping our testing environment to Ubuntu 22.04 from 20.04, Windows 2022 from 2019, and MacOS 12 from 11, and will now track updated environments.
- The …
=> GitHub runner updates

pygsti/extras/drift/signal.py
Replace the import of convolve from scipy to numpy. Fixes #391
=> Fix convolve import for scipy 3.12

test/test_packages/algorithms/test_germselection.py
This PR updates the germ selection correctness/integration checks added to the unit tests in `test_packages` in a recent update to develop. These tests can be sensitive to various difference among OS and python version and so were failing on some runners. Additional solutions have been added to the tests to account for these local variations, and we now have all of the tests in the `test_packages` workflow passing. With the exception of python 3.11 on macOS which is failing because of an unrelated build error with CVXOPT.
~Note: New commits are 52a793ddf1ccab2f71fd0df365caa4fde828b2aa and onward. The other commits are from the bugfix-stricter-line... branch which has already been merged in, but they still seem to show in the history as new in this branch.~ It is because I had accidentally …
=> Bugfix germsel correctness tests

pygsti/models/modelnoise.py, test/unit/objects/test_modelnoise.py
Depolarizing noise constructed with `depolarization_parameterization="lindblad"` doesn't match the same constructio when `depolarization_parameterization="depolarize"`, as demonstrated by the below code.  This is due to the use of the normalized Pauli basis (`"pp"`) where we should be using the un-normalized basis (`"PP"`).  This PR fixes this issue and adds a unit test.
To see the bug, run this (printed output should be the same but is not):
```
import pygsti
from pygsti.modelmembers.operations.opfactory import ComposedOpFactory
from pygsti.modelmembers.operations.depolarizeop import DepolarizeOp
pspec = pygsti.processors.QubitProcessorSpec(1, ["Gi"], geometry="line")
mdl1 = pygsti.models.create_crosstalk_free_model(
pspec,
depolarization_parameterization="lindblad", …
```
=> Fixes bug where depolarizing noise strength differs with parameterization

pygsti/baseobjs/opcalc/fastopcalc.pyx, pygsti/circuits/circuit.py, pygsti/data/datacomparator.py, pygsti/evotypes/densitymx/effectreps.pyx, pygsti/evotypes/densitymx/opreps.pyx, pygsti/evotypes/densitymx/statereps.pyx, pygsti/evotypes/stabilizer/statereps.pyx, pygsti/evotypes/statevec/effectreps.pyx, pygsti/evotypes/statevec/opreps.pyx, pygsti/evotypes/statevec/statereps.pyx, pygsti/protocols/vbdataframe.py, pygsti/report/fogidiagram.py, pygsti/tools/fastcalc.pyx, pygsti/tools/matrixmod2.py
Numpy 2.0 is about to be released and several deprecated attributes will be removed. In this PR we replace them with the preferred alternatives.
Also see: https://github.com/numpy/numpy/issues/24300, https://numpy.org/devdocs/numpy_2_0_migration_guide.html
=> Replace deprecated numpy.product, numpy.NaN and others

jupyter_notebooks/Examples/CirqIntegration.ipynb, pygsti/circuits/circuit.py, pygsti/modelpacks/smq1Q_ZN.py, pygsti/modelpacks/smq2Q_XXYYII.py, pygsti/modelpacks/smq2Q_XYXX.py, pygsti/modelpacks/smq2Q_XYZZ.py, pygsti/tools/internalgates.py, test/unit/objects/test_circuit.py
This PR updates the existing parser for conversion of pyGSTi Circuit objects to Cirq Circuit objects. Also introduced is a new parser for converting from Cirq Circuits objects into pyGSTi Circuit objects. A few other minor changes include:
1. Updates to pyGSTi's built-in gate definitions to include the following: 
- 'Giswap' and 'Gsqrtiswap' (2-qubit gates commonly used on superconducting platforms)
- 'Gcres' and 'Gecres' (2-qubit cross-resonance and echoed cross-resonance gates, respectively, native on many platforms including IBM's)
-  'Gn' (one-qubit N gate, a pi/2 rotation about the (np.sqrt(3)/2, 0, -1/2) axis of the Bloch sphere, commonly used native gate in some silicon qubit platforms, the N referred to in the smq1Q_ZN modelpack), 
- 'Gxpi4', 'Gypi4', 'Gzpi4' (pi/4 rotations above …
=> Update/New Cirq Parsing Capabilities

pygsti/tools/optools.py
Minor change: in `optools.entanglement_fidelity`, accept both arrays and gates for the `a` and `b` arguments. The arguments are cast to (dense) arrays within the function scope.
Perform similar casting in other functions, that call `a.shape`. 
See also #406.
Since some update (cannot pinpoint which exactly), this casting was not done anymore, neither within `optools.entanglement_fidelity`, nor in any of the functions calling this one.
I've chosen to cast to dense array within `optools.entanglement_fidelity`, rather than before calling this function, for two reasons:
- It keeps the number of changes as small as possible;
- It provides a more consistent interface across `optools`. Other functions (such as `average_gate_fidelity`, which calls `entanglement_fidelity`) accept arrays or gates. …
=> Cast gates to dense matrices in `optools`

pygsti/algorithms/fiducialselection.py
This is a quick bugfix for issue #396. The fix here is to simply force each of the line labels for candidate fiducial circuits to match the state space labels of the input target model. This is a suboptimal fix looking forward to many-qubit systems (as I mentioned in a comment on #396), but we don't presently have the infrastructure needed for doing this a better way and this fix should be fine for 99% of use cases with ExplicitOpModels in the few-qubit setting.
=> Bugfix for fiducial circuit line labels

pygsti/algorithms/core.py, pygsti/data/dataset.py
This PR covers two bugfixes. The first is in the method for adding cirq trials to pygsti datasets which did not behave as expected for 2+ qubits. The default behavior of the histogram method of the cirq `Result` object, which is used for gathering aggregated counts for each measurement results is to index these results using integers corresponding to the binary string for an outcome. In pygsti we more commonly use the binary strings themselves as the key. To address this we have added new options to `add_cirq_trial_result` which controls conversion back to a bit string before adding it to the count dictionary.
The second bugfix was to the LGST routine in order to patch in support for datasets with sparse formats wherein we only include outcomes with non-zero counts in the count dict for a …
=> Bugfix Cirq Datasets and LGST Bug

.gitignore, jupyter_notebooks/Examples/Leakage.ipynb, jupyter_notebooks/Tutorials/algorithms/GST-Protocols.ipynb, jupyter_notebooks/Tutorials/reporting/ProceduralErrorBars.ipynb, pygsti/algorithms/fiducialselection.py, pygsti/data/dataset.py, pygsti/protocols/gst.py, pygsti/report/templates/offline/pygsti_dashboard.css, pygsti/report/templates/offline/pygsti_dashboard.js, pygsti/report/workspaceplots.py
This PR contains three minor bugfixes slated for 0.9.12.2:
1. Tutorial updates for #317 
2. A revamp of the leakage example notebook following broken tests from PR #418
3. Additional labels to indicate report figure/table titles can be clicked for #416 
The leakage notebook may not be in a completely finished state. These updates are more or less making it so that circuit line labels are explicit, but it's a little awkward/still not working completely, especially for the kite structure example at the bottom. Suggestion now are welcome, or we can just slate it reworking later.
=> Bugfix 0.9.12.2

pygsti/algorithms/contract.py, pygsti/baseobjs/basis.py, pygsti/modelmembers/operations/__init__.py, pygsti/modelmembers/operations/fullcptpop.py, pygsti/modelmembers/states/__init__.py, pygsti/modelmembers/states/cptpstate.py, pygsti/report/reportables.py, pygsti/tools/basistools.py, pygsti/tools/jamiolkowski.py, pygsti/tools/lindbladtools.py, pygsti/tools/matrixtools.py, pygsti/tools/optools.py, test/unit/tools/test_basisconstructors.py, test/unit/tools/test_optools.py
Changes:
* Remove frobeniusnorm and frobeniusnorm_squared functions (which were only correct for real inputs). Inline equivalent numpy functions in the few places they were used.
* Replace the np.trace(np.dot(...)) pattern for computing the trace inner product with np.vdot(...). This resolves #430.
* Note that use of np.vdot has a secondary affect of conjugating the first argument when dealing with complex inputs. This resolves a limitation of basis conversion discussed in an email thread titled _Re: Possible pyGSTi bugs w/rt converting between matrix bases?_ that Robin started on Feb 23 of this year.
* I rewrote our implementation for computing state fidelity. It no longer needs the ``_hack_sqrtm`` function. It also has $O(n^2)$ time checks for the fidelity formulas when one of the …
=> Bugfixes and efficiency improvements for basis conversion, inner products, and computing Frobenius distance

pygsti/algorithms/randomcircuit.py, pygsti/circuits/circuit.py, pygsti/protocols/rb.py, pygsti/protocols/vb.py, test/unit/protocols/test_protocols.py, test/unit/protocols/test_rb.py
Fixes several RB issues. I still plan to write a few tests for these, but it is at least ready to review from the RB codeowners to ensure that these are good solutions to the features.
The desire was to be able to do deterministic Clifford compilation when generating `CliffordRBDesign` objects. We actually already had a partial way to do this because the `CliffordCompilationRules` are more or less exactly this - a rule for how to build up a circuit from native gates that implement a Clifford. So my implementation is just to add a `exact_compilation_key` kwarg which uses the compilation rules to do this deterministic compilation when provided, and otherwise to do the previous behavior of synthesizing using the random algorithms.
An example:
```
import pygsti
from pygsti.processors import …
```
=> RBDesign bugfixes and improvements

pygsti/modelmembers/states/__init__.py
The import of `isin` used is not availabe in numpy 2.0. If the import is required for backwards compatibility, then I suggest to replace it with `from numpy import isin`
=> Remove unused isin 

pygsti/circuits/circuit.py, pygsti/tools/internalgates.py
Should fix #440 by adding an ECR macro when ECR gates are detected.
This change should be primarily independent of anything in #379.
=> Add ECR support to QASM translation

jupyter_notebooks/Tutorials/algorithms/RB-CliffordRB.ipynb, pygsti/protocols/protocol.py, pygsti/protocols/rb.py, pygsti/protocols/vb.py, pygsti/tools/nameddict.py, test/unit/protocols/test_rb.py
This PR adds first party support for interleaved randomized benchmarking (as described in the original 2012 paper from Magesan et al. https://arxiv.org/pdf/1203.4550) to the RB codebase. The analysis for IRB is incredibly simple, so from an implementation standpoint much of what has been added is aimed at streamlining the experiment design construction process, automating this analysis, and creating data structures for keeping the two relevant subexperiments stored together.
Specifically I have added the following:
1. `InterleavedRBDesign`: This class both performs the creation of the two subexperiment designs (a standard CRB experiment and one with a target gate interleaved between random cliffords) and acts as a container for these two experiment designs. This subclasses off of …
=> Interleaved RB

.gitignore, pygsti/circuits/circuit.py, pygsti/optimize/customlm.py
Small bugfixes:
- Guarding setting SIGINT via `signal` in the customlm code. Needed in order to use pyGSTi with some external parallelization frameworks, such as Dask.
- Fixing unit tests by including a `Label.is_simple()` to `Label.IS_SIMPLE` that was missed.
=> Bugfix guard signal

pygsti/circuits/circuitparser/__init__.py, pygsti/models/qutrit.py
We use raw docstrings to avoid some escape sequence warnings. Using double slashes is also an option, but makes the plain docstring a bit harder to read.
=> Fix invalid escape sequence warnings

pygsti/modelpacks/smq2Q_XY.py, pygsti/modelpacks/smq2Q_XYI.py, pygsti/modelpacks/smq2Q_XYICNOT.py, pygsti/modelpacks/smq2Q_XYICPHASE.py, pygsti/modelpacks/smq2Q_XYZICNOT.py
This PR fixes some mismatches between the documentation for some of the two-qubit modelpacks, as well as the gate list attribute, and their actual contents.
This issue was reported in #497. Thanks to @eendebakpt for bringing the issue to our attention!
=> Fix docstrings and gate attribute

pygsti/tools/edesigntools.py, test/unit/tools/test_edesigntools.py
TLDR: This PR updates the implementation of the fisher information for experiment designs to support models/circuits with quantum instruments. This was requested ages ago in #464.
As part of updating the fisher information related code to support instruments this PR also changes the way that we do regularization. Previously this regularization was managed by adding a small amount of depolarizing error to the SPAM operations. Following a recommendation from @robinbk this has been changed to instead perform regularization by setting a minimum value for the probability p_min such that any probability below this threshold is clipped to this minimum value. As such, while in my testing the results looked nearly identical to previously calculated fisher information matrices for known experiment …
=> Fisher Information for Instruments

pygsti/modelmembers/operations/lindbladerrorgen.py, test/test_packages/drivers/test_drivers.py
This fixes a bug/unexpected behavior in the serialization/deserialization of CPTP parameterized models which use the cholesky decomposition to store the values of the SCA coefficient block. Due to sign ambiguity it was the case that serializing and deserializing a model could result in a sign change for some parameters. While this wasn't necessarily wrong (both choices of sign map to the same operation), not being able to rely on these being the same could lead to weird edge cases and unexpected behavior. This addresses that by adding the parameter value attribute for the error generator to the serialized json.
Fixes issue #341.
=> CPTP Serialization Sign Change Fix

pygsti/modelmembers/operations/lindbladcoefficients.py
This code hasn't been accessed much or at all recently, and it's likely when we refactored code to create the `LindbladCoefficientBlock` a long time ago this function was incorrectly updated to use the full number of parameters in places where it should have used the square root of this number (!).  This commit fixes this error and allows `superop_hessian_wrt_params` to run at least without getting IndexErrors.
The code is also validated by giving very close output to the same call using the non-dense evotype code.  Specifically, I ran this:
```
import pygsti
import numpy as np
from pygsti.modelpacks import smq1Q_XY
from pygsti.evotypes import Evotype
circuits = smq1Q_XY.create_gst_experiment_design(1).all_circuits_needing_data
test_circuit = circuits[-1]
target_model = …
```
=> Fixes array-dimension bug within LindbladCoefficientBlock.superop_hessian_wrt_params()

pygsti/circuits/cloudcircuitconstruction.py
If you run the tests under test_packages you'll see a deprecation warning of the following form
```
test/test_packages/drivers/test_nqubit.py: 22 warnings
/Users/rjmurr/Documents/pygsti-general/pyGSTi/pygsti/circuits/cloudcircuitconstruction.py:2167: DeprecationWarning: `np.math` is a deprecated alias for the standard library `math` module (Deprecated Numpy 1.25). Replace usages of `np.math` with `math`
half = [bitstr(n, k) for k in range(int(_np.ceil(_np.math.log(n, 2))))]
```
This tiny PR resolves this issue by replacing ``_np.math.log(n, 2)`` with ``_np.log2(n)``.
=> Resolve deprecation warning for use of _np.math.log.

pygsti/protocols/gst.py, pygsti/tools/optools.py
This adds partial support for adding wildcard models to estimates containing quantum instruments. At the moment this only patches in support for 1D diamond distance wildcard models. This addresses issue #463.
An additional change is that a slightly different version of the instrument fidelity and instrument diamond distance functions in reportables have been copied over to optools for better discoverability. For a separate thread on eventually reconciling those two files see #526.
=> Wildcard Support for Instruments

pygsti/data/dataset.py, pygsti/io/stdinput.py
This fixes #535 by having `add_count_list` call `add_count_dict`, which handles the outcome label sorting properly. This has the advantage of minimizing code duplication before the `add_raw_series_data` call.
I have not migrated `add_count_arrays` because that uses `add_raw_arrays` instead, but in principle it can also be transition to use `add_count_dict` and therefore centralize all the `collisionAction == "aggregate"` code.
=> Fix DataSet.add_count_list() outcome label misordering

pygsti/algorithms/fiducialpairreduction.py, pygsti/algorithms/germselection.py, pygsti/modelmembers/operations/lindbladcoefficients.py, test/unit/algorithms/test_germselection.py
Three quick bugfixes:
1. Per-germ global FPR requires the matrix forward simulator for some subroutines, but the default forward simulator for models is now map. We now automatically make a copy of the model with the correct forward simulator as needed. Also for pgg FPR, fix to account for change to previously changed return value format when not passing in a precomputed germ spanning vector set. The same fix was also made to the `germ_set_spanning_vectors` function.
2. The change for germ selection line-labels in PR #540 introduced a bug caught by some annoyingly nondeterministic unit test failures. Germ selection returning None is a valid outcome when the initial candidate germ set is not amplificationally complete and we weren't checking for that case when doing the line label …
=> Bugfixes for PGG FPR and Germ Selection

pygsti/algorithms/randomcircuit.py
This addresses issue #546 and adds in the rest of the plumbing needed for deterministically random BiRB experiment design construction. Previously even when specifying a seed this wasn't being propagated through to all of the different random sampling steps (or in some cases these sampling steps weren't configured to take a seed) meaning that the results were unexpectedly still non-deterministic (which is a problem where reproducibility guarantees are required.
=> Add seeding for BiRB designs

pygsti/baseobjs/label.py, pygsti/models/explicitmodel.py, pygsti/report/reportables.py
This contains the following minor bugfixes for 0.9.13.1:
- Basis casting for #455
- Numpy array size check deprecation fix for #514 
- Explicit use of dense rep of gates in randomize_with_unitary() for #481
=> Final bugfixes for 0.9.13.1

pygsti/circuits/gstcircuits.py
This changes the way the LGST circuits are stored when using FPR. Previously these were stripped from the plaquettes and any needed circuits were added back in in `_additional_circuits`. Now we just don't remove those for L=1 if we shouldn't. This addresses a bug reported by @pcwysoc that was present in the color box plots where the result of the old behavior was that these LGST circuits weren't rendered with the plaquettes as expected.
=> Change LGST Circuit Storage with FPR (Color Boxplot Fix)

pygsti/tools/internalgates.py
Added labels for all 24 single-qubit Clifford gates to internalgates.py. The labels show the decomposition of each Clifford gate into the gates {I, X, Y, Z, H, P, Pdag}.
=> Add Clifford Labels to interalgates.py

pygsti/baseobjs/errorgenbasis.py
Resolves issue #579
Makes sure that some sets utilized within setup_fogi get sorted before they re utilized, resulting canonical/deterministic FOGI models
=> Bugfix deterministic fogi

pygsti/report/workspace.py
This addresses what looks to be an expired module name alias deprecation in Ipython 9.0 for the `core.display` module.
This issue, and the fix identified here, was kindly reported in #593 by @liuyichao82.
=> Ipython 9.0 Deprecation

pyproject.toml
This patches a configuration error with the pyproject.toml file that meant the expected _version.py file was not being autogenerated.
=> Add version file directive to pyproject

pygsti/processors/processorspec.py
Any usage of `rename_gate_inplace` breaks since `items()` was missing in the dict comprehensions
=> Fix dictionary comprehension for gate unitary renaming in QuditProcessorSpec

pygsti/modelmembers/operations/embeddederrorgen.py, pygsti/modelmembers/operations/experrorgenop.py, pygsti/modelmembers/operations/fulltpop.py, pygsti/modelmembers/operations/lindbladcoefficients.py, pygsti/modelmembers/operations/lindbladerrorgen.py, pygsti/models/gaugegroup.py, test/unit/objects/test_gaugegroup.py
This is pulled out of PR #410. The main change is the new gauge group which handles subgroups of unitaries that have a block-diagonal structure. Along the way I added type annotations throughout error generator code. I also cleaned up code in LindbladCoefficientBlock._block_data_to_params.
=> New gauge group, plus minor changes to error generator classes

pygsti/modelpacks/smq1Q_XZ.py
It was recently pointed out by some external collaborators (and subsequently reported in #585) that there was an error on the preparation and measurement fiducials which made it such that, whereas the structure of the XZ modelpack's fiducials should have had a 6x6 structure, mapping the |0> state to each of the cardinal axes of the Bloch sphere, one of the fiducials was accidentally duplicitous of another (meaning we effectively only had 5 unique fiducials). Fortunately they were still IC, which minimized the amount of egg on face incurred.
This PR fixes the prep and measurement fiducials, updates the robust and standard germ sets, and recomputes the pre-computed FPR sets to account for the changes. For backwards compatibility there is a flag that can be set manually in the code to …
=> Fix XZ Modelpack

pygsti/modelmembers/instruments/tpinstrument.py, pygsti/processors/processorspec.py, pygsti/report/workspaceplots.py
Hi Corey,
This should address the remainder of your email. There are three one line fixes:
1) Correcting the threshold calculation for the per sequence detail plot to use the number of circuits not the number of boxes.
2) Addressing a typo that means quantum instruments fail to deserialize correctly. 
3) Fixing a bug where integer qubit labels used with quantum instruments fail to serialize correctly.
=> Per seq threshold and miscellaneous QI serialization fixes

pygsti/tools/internalgates.py
This propagates the new gate alias for the Gecr gate to a few more places in internalgates, following up on #609.
=> More Gecr Aliases

pygsti/circuits/circuit.py, pygsti/errorgenpropagation/errorpropagator.py, pygsti/tools/errgenproptools.py, pygsti/tools/internalgates.py, test/unit/objects/test_circuit.py, test/unit/objects/test_errorgenpropagation.py, test/unit/tools/test_errgenproptools.py
This PR adds three new features/updates to the error generator propagation module:
1. Support for the analytic computation of Magnus expansions has been added and replaces the default behavior when computing the BCH approximation for an end-of-circuit error generator. The new implementation supports up to third-order in the Magnus expansion. The previous method, iterative pairwise application of the BCH approximation is still available, but is no longer the default method. A corresponding numerical implementation has been added to support new unit tests.
2. The logic for automatically mapping pyGSTi circuit line labels into the form required for conversion into a `stim.Tableau` has been extended to support automatic inference for the vast majority of use cases. For tricky or edge cases …
=> Magnus Expansions, Better Tableau Inference, and Errorgens on Paulis

pygsti/tools/dataframetools.py
Single line fix to convert pandas CategoricalIndex to a normal Index, which seems necessary for `pandas.merge` to function as intended after a recent update (of pandas).  This issue was causing "`KeyError: slice(None, None, None)` failures when trying to convert results objects to pandas DataFrames, failing within `_to_dataframe(...)` calls.
=> Adds fix for pandas "KeyError: slice(None, None, None)" failures.

test/unit/extras/ibmq/test_ibmqexperiment.py, test/unit/protocols/test_protocols.py
Re-enable unit tests which now should work with #636 fixed.
=> Reenable Tests Involving Dataframes

pygsti/objectivefns/objectivefns.py
While playing around with MPI parallelization across parameters (instead of circuits, which the default for the map simulator as of 0.9.13) I ran into a bug which I tracked down to a shared memory bug inadvertently introduced with PR #515. Attached is a script, which if run using MPI (I was using 4 ranks) runs a single iteration of two-qubit GST on a single thread and on all four threads and logs the result for comparison. [debug_dist_objective_fn.py](https://github.com/user-attachments/files/22715098/debug_dist_objective_fn.py). Running this script on 0.9.14.1 yields the following output:
```
Number of Ranks is 4
Fit Log Single Rank
-----------------------------
Precomputing CircuitOutcomeProbabilityArray layouts for each iteration.
Layout for iteration 0
Num Param Processors (1,) …
```
=> Shared Memory Bug

pygsti/objectivefns/objectivefns.py
Note: For some reason the automatic merge from bugfix into develop failed on PR #660, so this PR is just manually performing that merge.
While playing around with MPI parallelization across parameters (instead of circuits, which the default for the map simulator as of 0.9.13) I ran into a bug which I tracked down to a shared memory bug inadvertently introduced with PR #515. Attached is a script, which if run using MPI (I was using 4 ranks) runs a single iteration of two-qubit GST on a single thread and on all four threads and logs the result for comparison. [debug_dist_objective_fn.py](https://github.com/user-attachments/files/22715098/debug_dist_objective_fn.py). Running this script on 0.9.14.1 yields the following output:
```
Number of Ranks is 4
Fit Log Single Rank …
```
=> Shared Memory Bug (#660) (Merge Into Develop)
